name: Deploy to AWS EKS Cluster

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Image Versions
      run: |
        echo "WHOAMI_NODEJS_IMAGE_VERSION=latest" >> $GITHUB_ENV
        echo "WHOAMI_IMAGE_VERSION=v1.0.0" >> $GITHUB_ENV

    - name: Update manifest file with image versions
      run: |
        sed -i "s|image: congtaojiang/whoami-nodejs-express.*|image: congtaojiang/whoami-nodejs-express:${{ env.WHOAMI_NODEJS_IMAGE_VERSION }}|" kubernetes/deployment.yaml
        sed -i "s|image: emilevauge/whoami.*|image: emilevauge/whoami:${{ env.WHOAMI_IMAGE_VERSION }}|" kubernetes/canary-deployment.yaml

    - name: Check for Changes
      run: |
        git diff --exit-code kubernetes/deployment.yaml kubernetes/canary-deployment.yaml || git commit -am "Update deployment manifest with image versions"

    - name: Install AWS CLI and kubectl
      run: |
        apt-get update
        apt-get install -y awscli kubectl
      continue-on-error: false

    - name: Configure AWS Credentials
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        if [ -z "$AWS_REGION" ] || [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "AWS credentials or region are not properly set"
          exit 1
        fi
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

    - name: Update kubeconfig for EKS
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $AWS_EKS_CLUSTER_NAME || { echo 'Failed to update kubeconfig'; exit 1; }

    - name: Apply Kubernetes Configs
      run: |
        set -e
        for file in kubernetes/deployment.yaml kubernetes/service.yaml kubernetes/canary-deployment.yaml kubernetes/canary-service.yaml; do
          kubectl apply -f $file || { echo "Failed to apply $file"; exit 1; }
        done
      continue-on-error: false

    - name: Wait for Deployment to be Ready
      run: |
        kubectl rollout status deployment/whoami-deployment --timeout=60s || { echo "whoami-deployment rollout failed"; exit 1; }
        kubectl rollout status deployment/whoami-canary --timeout=60s || { echo "whoami-canary rollout failed"; exit 1; }

    - name: Verify Deployment Health
      run: |
        echo "Verifying pod status..."
        kubectl get pods || { echo "Failed to get pod information"; exit 1; }
        echo "Verifying services..."
        kubectl get services || { echo "Failed to get services information"; exit 1; }

    - name: Rollback on Failure
      if: failure()
      run: |
        echo "Rolling back due to failure..."
        kubectl rollout undo deployment/whoami-deployment
        kubectl rollout undo deployment/whoami-canary

    - name: Notify on Success
      if: success()
      run: echo "Deployment succeeded!"

    - name: Notify on Failure
      if: failure()
      run: echo "Deployment failed!"
