name: Deploy to AWS EKS Cluster

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      WHOAMI_IMAGE_VERSION: "v1.0.0"
      WHOAMI_NODEJS_IMAGE_VERSION: "latest"
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update manifest file with image versions
      run: |
        sed -i "s|image: congtaojiang/whoami-nodejs-express.*|image: congtaojiang/whoami-nodejs-express:${WHOAMI_NODEJS_IMAGE_VERSION}|" kubernetes/base-deployment.yaml
        sed -i "s|image: emilevauge/whoami.*|image: emilevauge/whoami:${WHOAMI_IMAGE_VERSION}|" kubernetes/canary-deployment.yaml

    - name: Configure Git Identity
      run: |
        git config --global user.email "$USER_EMAIL"
        git config --global user.name "$USER_NAME"

    - name: Check for Changes
      run: |
        git diff --exit-code kubernetes/base-deployment.yaml kubernetes/canary-deployment.yaml || git commit -am "Update deployment manifest with image versions"

    - name: Install AWS CLI and kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli kubectl
      continue-on-error: false

    - name: Configure AWS Credentials
      run: |
        if [ -z "$AWS_REGION" ] || [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "AWS credentials or region are not properly set"
          exit 1
        fi
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $AWS_EKS_CLUSTER_NAME || { echo 'Failed to update kubeconfig'; exit 1; }

    - name: Apply Kubernetes Configs
      run: |
        set -e
        kubectl apply -f kubernetes/ || { echo "Failed to apply Kubernetes configs"; exit 1; }
      continue-on-error: false

    - name: Wait for Deployment to be Ready
      run: |
        kubectl rollout status deployment/base-app --timeout=60s || { echo "base-app rollout failed"; exit 1; }
        kubectl rollout status deployment/canary-app --timeout=60s || { echo "canary-app rollout failed"; exit 1; }

    - name: Verify Deployment Health
      run: |
        echo "Verifying pod status..."
        kubectl get pods || { echo "Failed to get pod information"; exit 1; }
        echo "Verifying services..."
        kubectl get services || { echo "Failed to get services information"; exit 1; }
        echo "Verifying deployments..."
        kubectl get deployments || { echo "Failed to get deployments information"; exit 1; }

    - name: Notify on Success
      if: success()
      run: echo "Deployment succeeded!"

    - name: Notify on Failure
      if: failure()
      run: echo "Deployment failed!"
